project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3a"
          href: "Hands-on_Ex/Hands-on_Ex03a/Hands-on_Ex03a.html"
        - text: "Hands-on Exercise 3b"
          href: "Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.html"
        - text: "Hands-on Exercise 4a"
          href: "Hands-on_Ex/Hands-on_Ex04a/Hands-on_Ex04a.html"
        - text: "Hands-on Exercise 4b"
          href: "Hands-on_Ex/Hands-on_Ex04b/Hands-on_Ex04b.html"
        - text: "Hands-on Exercise 4c"
          href: "Hands-on_Ex/Hands-on_Ex04c/Hands-on_Ex04c.html"
        - text: "Hands-on Exercise 4d"
          href: "Hands-on_Ex/Hands-on_Ex04d/Hands-on_Ex04d.html"
        - text: "Hands-on Exercise 5a"
          href: "Hands-on_Ex/Hands-on_Ex05a/Hands-on_Ex05a.html"
        - text: "Hands-on Exercise 5b"
          href: "Hands-on_Ex/Hands-on_Ex05b/Hands-on_Ex05b.html"
        - text: "Hands-on Exercise 5c"
          href: "Hands-on_Ex/Hands-on_Ex05c/Hands-on_Ex05c.html"
        - text: "Hands-on Exercise 5d"
          href: "Hands-on_Ex/Hands-on_Ex05d/Hands-on_Ex05d.html"
        - text: "Hands-on Exercise 5e"
          href: "Hands-on_Ex/Hands-on_Ex05e/Hands-on_Ex05e.html"
        - text: "Hands-on Exercise 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "Hands-on Exercise 8a"
          href: "Hands-on_Ex/Hands-on_Ex08a/Hands-on_Ex08a.html"  
        - text: "Hands-on Exercise 8b"
          href: "Hands-on_Ex/Hands-on_Ex08b/Hands-on_Ex08b.html" 
        - text: "Hands-on Exercise 8c"
          href: "Hands-on_Ex/Hands-on_Ex08c/Hands-on_Ex08c.html" 
        - text: "Hands-on Exercise 9"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html" 
        - text: "Hands-on Exercise 10"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html" 
          
    - text: "Take-Home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"    
        - text: "Take-home Exercise 3a"
          href: "Take-home_Ex/Take-home_Ex03a/Take-home_Ex03a.html"           
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In-class Exercise 5"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
        - text: "In-class Exercise 7"
          href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html" 
        - text: "In-class Exercise 8"
          href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"     
        - text: "In-class Exercise 9"
          href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"   
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

