<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="WANG XINGYUN">

<title>Take-home_Ex01 – ISSS608-VAA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS608-VAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03a/Hands-on_Ex03a.html">
 <span class="dropdown-text">Hands-on Exercise 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.html">
 <span class="dropdown-text">Hands-on Exercise 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04a/Hands-on_Ex04a.html">
 <span class="dropdown-text">Hands-on Exercise 4a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04b/Hands-on_Ex04b.html">
 <span class="dropdown-text">Hands-on Exercise 4b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04c/Hands-on_Ex04c.html">
 <span class="dropdown-text">Hands-on Exercise 4c</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04d/Hands-on_Ex04d.html">
 <span class="dropdown-text">Hands-on Exercise 4d</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05a/Hands-on_Ex05a.html">
 <span class="dropdown-text">Hands-on Exercise 5a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05b/Hands-on_Ex05b.html">
 <span class="dropdown-text">Hands-on Exercise 5b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05c/Hands-on_Ex05c.html">
 <span class="dropdown-text">Hands-on Exercise 5c</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05d/Hands-on_Ex05d.html">
 <span class="dropdown-text">Hands-on Exercise 5d</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05e/Hands-on_Ex05e.html">
 <span class="dropdown-text">Hands-on Exercise 5e</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#creating-data-visualisation-beyond-default-heart-attack-in-japan-youth-vs-adult" id="toc-creating-data-visualisation-beyond-default-heart-attack-in-japan-youth-vs-adult" class="nav-link active" data-scroll-target="#creating-data-visualisation-beyond-default-heart-attack-in-japan-youth-vs-adult">Creating data visualisation beyond default: <strong>Heart Attack in Japan Youth Vs Adult</strong></a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><strong>Overview</strong></a>
  <ul class="collapse">
  <li><a href="#setting-the-scene" id="toc-setting-the-scene" class="nav-link" data-scroll-target="#setting-the-scene"><strong>Setting the scene</strong></a></li>
  </ul></li>
  <li><a href="#our-task" id="toc-our-task" class="nav-link" data-scroll-target="#our-task">Our task</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">Getting started</a>
  <ul class="collapse">
  <li><a href="#load-package" id="toc-load-package" class="nav-link" data-scroll-target="#load-package">load package</a></li>
  <li><a href="#import-data" id="toc-import-data" class="nav-link" data-scroll-target="#import-data">Import data</a></li>
  <li><a href="#dataset-overview" id="toc-dataset-overview" class="nav-link" data-scroll-target="#dataset-overview"><strong>Dataset Overview</strong></a></li>
  <li><a href="#data-pre-processing" id="toc-data-pre-processing" class="nav-link" data-scroll-target="#data-pre-processing">Data pre-processing</a></li>
  </ul></li>
  <li><a href="#eda-1-heart-attack-occurrence-by-age-distribution" id="toc-eda-1-heart-attack-occurrence-by-age-distribution" class="nav-link" data-scroll-target="#eda-1-heart-attack-occurrence-by-age-distribution">EDA 1 Heart Attack Occurrence by Age Distribution</a>
  <ul class="collapse">
  <li><a href="#key-observations" id="toc-key-observations" class="nav-link" data-scroll-target="#key-observations"><strong>Key Observations:</strong></a></li>
  </ul></li>
  <li><a href="#eda-2-heart-attack-occurrence-by-age-group" id="toc-eda-2-heart-attack-occurrence-by-age-group" class="nav-link" data-scroll-target="#eda-2-heart-attack-occurrence-by-age-group">EDA 2 Heart Attack Occurrence by Age Group</a>
  <ul class="collapse">
  <li><a href="#key-observations-1" id="toc-key-observations-1" class="nav-link" data-scroll-target="#key-observations-1"><strong>Key Observations:</strong></a></li>
  <li><a href="#key-observations-2" id="toc-key-observations-2" class="nav-link" data-scroll-target="#key-observations-2"><strong>Key Observations:</strong></a></li>
  </ul></li>
  <li><a href="#eda-2-the-relationship-between-gender-and-heart-attack" id="toc-eda-2-the-relationship-between-gender-and-heart-attack" class="nav-link" data-scroll-target="#eda-2-the-relationship-between-gender-and-heart-attack">EDA 2 The relationship between gender and heart attack</a>
  <ul class="collapse">
  <li><a href="#key-observations-3" id="toc-key-observations-3" class="nav-link" data-scroll-target="#key-observations-3"><strong>Key Observations:</strong></a></li>
  </ul></li>
  <li><a href="#eda3-calculate-the-incidence-rate-of-heart-disease-in-different-regions" id="toc-eda3-calculate-the-incidence-rate-of-heart-disease-in-different-regions" class="nav-link" data-scroll-target="#eda3-calculate-the-incidence-rate-of-heart-disease-in-different-regions">EDA3 Calculate the incidence rate of heart disease in different regions</a></li>
  <li><a href="#eda4-the-relationship-between-health-conditions-and-heart-attack-occurrence" id="toc-eda4-the-relationship-between-health-conditions-and-heart-attack-occurrence" class="nav-link" data-scroll-target="#eda4-the-relationship-between-health-conditions-and-heart-attack-occurrence">EDA4 The relationship between health conditions and heart attack occurrence</a>
  <ul class="collapse">
  <li><a href="#calculate-heart-attack-rates-for-each-health-factor" id="toc-calculate-heart-attack-rates-for-each-health-factor" class="nav-link" data-scroll-target="#calculate-heart-attack-rates-for-each-health-factor">1.Calculate heart attack rates for each health factor</a></li>
  <li><a href="#key-observations-4" id="toc-key-observations-4" class="nav-link" data-scroll-target="#key-observations-4"><strong>Key Observations:</strong></a></li>
  <li><a href="#analyze-the-impact-of-continuous-variables-cholesterol-bmi" id="toc-analyze-the-impact-of-continuous-variables-cholesterol-bmi" class="nav-link" data-scroll-target="#analyze-the-impact-of-continuous-variables-cholesterol-bmi">2.Analyze the Impact of Continuous Variables (Cholesterol, BMI)</a></li>
  <li><a href="#key-observations-5" id="toc-key-observations-5" class="nav-link" data-scroll-target="#key-observations-5"><strong>Key Observations:</strong></a></li>
  <li><a href="#draw-a-heat-map" id="toc-draw-a-heat-map" class="nav-link" data-scroll-target="#draw-a-heat-map">3. Draw a heat map</a></li>
  <li><a href="#key-observations-6" id="toc-key-observations-6" class="nav-link" data-scroll-target="#key-observations-6"><strong>Key Observations:</strong></a></li>
  </ul></li>
  <li><a href="#eda5-the-relationship-between-stress-level-and-heart-attack-occurrence" id="toc-eda5-the-relationship-between-stress-level-and-heart-attack-occurrence" class="nav-link" data-scroll-target="#eda5-the-relationship-between-stress-level-and-heart-attack-occurrence">EDA5 The relationship between stress level and heart attack occurrence</a></li>
  <li><a href="#eda6-exploring-the-impact-of-lifestyle-level-of-physical-activitydietary-qualityalcohol-intake-on-the-onset-of-heart-disease" id="toc-eda6-exploring-the-impact-of-lifestyle-level-of-physical-activitydietary-qualityalcohol-intake-on-the-onset-of-heart-disease" class="nav-link" data-scroll-target="#eda6-exploring-the-impact-of-lifestyle-level-of-physical-activitydietary-qualityalcohol-intake-on-the-onset-of-heart-disease">EDA6 Exploring the impact of lifestyle (level of physical activity\dietary quality\alcohol intake) on the onset of heart disease</a>
  <ul class="collapse">
  <li><a href="#the-impact-of-physical-activity-level-on-heart-attack" id="toc-the-impact-of-physical-activity-level-on-heart-attack" class="nav-link" data-scroll-target="#the-impact-of-physical-activity-level-on-heart-attack">1. The impact of physical activity level on heart attack</a></li>
  <li><a href="#the-impact-of-dietary-quality-on-heart-attack" id="toc-the-impact-of-dietary-quality-on-heart-attack" class="nav-link" data-scroll-target="#the-impact-of-dietary-quality-on-heart-attack">2. The impact of Dietary quality on heart attack</a></li>
  </ul></li>
  <li><a href="#summary-and-conclusion" id="toc-summary-and-conclusion" class="nav-link" data-scroll-target="#summary-and-conclusion">Summary and conclusion</a></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference:</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home_Ex01</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>WANG XINGYUN </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="creating-data-visualisation-beyond-default-heart-attack-in-japan-youth-vs-adult" class="level1">
<h1>Creating data visualisation beyond default: <strong>Heart Attack in Japan Youth Vs Adult</strong></h1>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview"><strong>Overview</strong></h2>
<section id="setting-the-scene" class="level3">
<h3 class="anchored" data-anchor-id="setting-the-scene"><strong>Setting the scene</strong></h3>
<p>Cardiovascular diseases are a growing global health concern, with heart attacks being one of the leading causes of morbidity and mortality. Understanding the risk factors and health profiles associated with heart attacks is crucial for developing targeted prevention strategies. This dataset provides a comprehensive analysis of heart attack occurrences in Japan, specifically comparing youth and adult age groups. By examining key health indicators, lifestyle choices, and medical histories, this dataset offers valuable insights into the distinct patterns and potential triggers of heart attacks across different demographics.</p>
</section>
</section>
<section id="our-task" class="level2">
<h2 class="anchored" data-anchor-id="our-task">Our task</h2>
<p>In this exercise, Exploratory Data Analysis (EDA) methods and ggplot functions are used to explore:</p>
<p>Whether the incidence rate of heart disease is different in different ages and genders, and whether there is a significant relationship between heart disease and various diseases, including whether lifestyle, eating habits, etc. affect the incidence rate of heart disease</p>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting started</h2>
<section id="load-package" class="level3">
<h3 class="anchored" data-anchor-id="load-package">load package</h3>
<p>For this exercise, we load the following R packages using the&nbsp;<code>pacman::p_load()</code>&nbsp;function</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, haven,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               ggrepel, ggthemes,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               ggridges, ggdist,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               patchwork, scales,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               corrr, ggcorrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="import-data" class="level3">
<h3 class="anchored" data-anchor-id="import-data">Import data</h3>
<p>In this section, we need to read this data-set</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/japan_heart_attack_dataset.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>check dataset structure and show the head data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   30000 obs. of  32 variables:
 $ Age                    : int  56 69 46 32 60 25 78 38 56 75 ...
 $ Gender                 : chr  "Male" "Male" "Male" "Female" ...
 $ Region                 : chr  "Urban" "Urban" "Rural" "Urban" ...
 $ Smoking_History        : chr  "Yes" "No" "Yes" "No" ...
 $ Diabetes_History       : chr  "No" "No" "No" "No" ...
 $ Hypertension_History   : chr  "No" "No" "No" "No" ...
 $ Cholesterol_Level      : num  186 185 211 211 224 ...
 $ Physical_Activity      : chr  "Moderate" "Low" "Low" "Moderate" ...
 $ Diet_Quality           : chr  "Poor" "Good" "Average" "Good" ...
 $ Alcohol_Consumption    : chr  "Low" "Low" "Moderate" "High" ...
 $ Stress_Levels          : num  3.64 3.38 3.81 6.01 6.81 ...
 $ BMI                    : num  34 28.2 27.6 23.7 19.8 ...
 $ Heart_Rate             : num  72.3 57.5 64.7 55.1 76.7 ...
 $ Systolic_BP            : num  124 130 146 132 101 ...
 $ Diastolic_BP           : num  85.7 73.5 72 68.2 92.9 ...
 $ Family_History         : chr  "No" "Yes" "No" "No" ...
 $ Heart_Attack_Occurrence: chr  "No" "No" "No" "No" ...
 $ Extra_Column_1         : num  0.405 0.0363 0.853 0.3909 0.9336 ...
 $ Extra_Column_2         : num  0.433 0.513 0.22 0.297 0.976 ...
 $ Extra_Column_3         : num  0.629 0.668 0.613 0.156 0.174 ...
 $ Extra_Column_4         : num  0.702 0.116 0.508 0.87 0.295 ...
 $ Extra_Column_5         : num  0.498 0.424 0.901 0.39 0.959 ...
 $ Extra_Column_6         : num  0.0079 0.0839 0.2272 0.4032 0.6898 ...
 $ Extra_Column_7         : num  0.795 0.689 0.496 0.741 0.905 ...
 $ Extra_Column_8         : num  0.291 0.83 0.752 0.224 0.757 ...
 $ Extra_Column_9         : num  0.497 0.634 0.182 0.329 0.338 ...
 $ Extra_Column_10        : num  0.522 0.302 0.629 0.143 0.362 ...
 $ Extra_Column_11        : num  0.7997 0.0437 0.0183 0.9078 0.7286 ...
 $ Extra_Column_12        : num  0.7224 0.4517 0.0632 0.5423 0.1767 ...
 $ Extra_Column_13        : num  0.149 0.879 0.147 0.922 0.485 ...
 $ Extra_Column_14        : num  0.834 0.536 0.997 0.626 0.312 ...
 $ Extra_Column_15        : num  0.0616 0.6178 0.9745 0.2286 0.4528 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Age Gender Region Smoking_History Diabetes_History Hypertension_History
1  56   Male  Urban             Yes               No                   No
2  69   Male  Urban              No               No                   No
3  46   Male  Rural             Yes               No                   No
4  32 Female  Urban              No               No                   No
5  60 Female  Rural              No               No                   No
6  25 Female  Rural              No               No                   No
  Cholesterol_Level Physical_Activity Diet_Quality Alcohol_Consumption
1          186.4002          Moderate         Poor                 Low
2          185.1367               Low         Good                 Low
3          210.6966               Low      Average            Moderate
4          211.1655          Moderate         Good                High
5          223.8143              High         Good                High
6          220.3400               Low         Good                High
  Stress_Levels      BMI Heart_Rate Systolic_BP Diastolic_BP Family_History
1      3.644786 33.96135   72.30153    123.9021     85.68281             No
2      3.384056 28.24287   57.45764    129.8933     73.52426            Yes
3      3.810911 27.60121   64.65870    145.6549     71.99481             No
4      6.014878 23.71729   55.13147    131.7852     68.21133             No
5      6.806883 19.77158   76.66792    100.6946     92.90249             No
6      8.207233 20.24744   67.66268    134.5966     73.14970             No
  Heart_Attack_Occurrence Extra_Column_1 Extra_Column_2 Extra_Column_3
1                      No     0.40498852      0.4333000      0.6287124
2                      No     0.03627815      0.5125669      0.6683928
3                      No     0.85297888      0.2195908      0.6134366
4                      No     0.39085280      0.2968468      0.1557240
5                      No     0.93356280      0.9756513      0.1737750
6                      No     0.52447124      0.2328291      0.5885502
  Extra_Column_4 Extra_Column_5 Extra_Column_6 Extra_Column_7 Extra_Column_8
1      0.7016095      0.4981423    0.007901312      0.7945826      0.2907792
2      0.1155287      0.4238194    0.083932768      0.6889511      0.8301636
3      0.5080100      0.9006698    0.227205241      0.4963436      0.7521068
4      0.8702514      0.3903559    0.403181621      0.7414089      0.2239681
5      0.2953319      0.9594067    0.689787430      0.9045740      0.7570983
6      0.4169773      0.1703778    0.448359048      0.3690557      0.1958173
  Extra_Column_9 Extra_Column_10 Extra_Column_11 Extra_Column_12
1      0.4971931       0.5219945      0.79965663      0.72239788
2      0.6344903       0.3020434      0.04368285      0.45166789
3      0.1815012       0.6291803      0.01827617      0.06322702
4      0.3293139       0.1431905      0.90778075      0.54232201
5      0.3377609       0.3623747      0.72855208      0.17669914
6      0.3959485       0.8354301      0.00359574      0.94144789
  Extra_Column_13 Extra_Column_14 Extra_Column_15
1       0.1487387       0.8340099     0.061632229
2       0.8786714       0.5356022     0.617825340
3       0.1465122       0.9972962     0.974455410
4       0.9224606       0.6262165     0.228606344
5       0.4847487       0.3120910     0.452808843
6       0.8757355       0.7186975     0.008745039</code></pre>
</div>
</div>
</section>
<section id="dataset-overview" class="level3">
<h3 class="anchored" data-anchor-id="dataset-overview"><strong>Dataset Overview</strong></h3>
<section id="data-size" class="level4">
<h4 class="anchored" data-anchor-id="data-size"><strong>📌 Data Size:</strong></h4>
<ul>
<li>The dataset consists of 30,000 rows and 32 columns.</li>
</ul>
</section>
<section id="key-variables" class="level4">
<h4 class="anchored" data-anchor-id="key-variables"><strong>📌 Key Variables:</strong></h4>
<p>1️⃣ <strong>Demographic Information:</strong></p>
<ul>
<li><p><code>Age</code> (years)</p></li>
<li><p><code>Gender</code> (Male/Female)</p></li>
<li><p><code>Region</code> (Geographical location)</p></li>
</ul>
<p>2️⃣ <strong>Health Conditions:</strong></p>
<ul>
<li><p><code>Smoking_History</code> (History of smoking)</p></li>
<li><p><code>Diabetes_History</code> (History of diabetes)</p></li>
<li><p><code>Hypertension_History</code> (History of hypertension)</p></li>
<li><p><code>Cholesterol_Level</code> (Cholesterol levels)</p></li>
<li><p><code>BMI</code> (Body Mass Index)</p></li>
</ul>
<p>3️⃣ <strong>Lifestyle Factors:</strong></p>
<ul>
<li><p><code>Physical_Activity</code> (Level of physical activity)</p></li>
<li><p><code>Diet_Quality</code> (Dietary quality)</p></li>
<li><p><code>Alcohol_Consumption</code> (Alcohol intake)</p></li>
</ul>
<p>4️⃣ <strong>Physiological Measurements:</strong></p>
<ul>
<li><p><code>Heart_Rate</code> (Heart rate)</p></li>
<li><p><code>Systolic_BP</code> (Systolic blood pressure)</p></li>
<li><p><code>Diastolic_BP</code> (Diastolic blood pressure)</p></li>
</ul>
<p>5️⃣ <strong>Heart Attack Occurrence:</strong></p>
<ul>
<li><code>Heart_Attack_Occurrence</code> (Indicates whether a heart attack occurred)</li>
</ul>
<p>This dataset provides a comprehensive view of demographic, health, lifestyle, and physiological factors that may influence heart attack occurrences. The analysis will explore potential correlations and risk factors associated with heart disease.</p>
</section>
</section>
<section id="data-pre-processing" class="level3">
<h3 class="anchored" data-anchor-id="data-pre-processing">Data pre-processing</h3>
<p>I found the many columns-“Extra_column” in this dataset, we try to check. We first take a look at the data, and check if there are any duplicate entries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 30,000
Columns: 32
$ Age                     &lt;int&gt; 56, 69, 46, 32, 60, 25, 78, 38, 56, 75, 36, 40…
$ Gender                  &lt;chr&gt; "Male", "Male", "Male", "Female", "Female", "F…
$ Region                  &lt;chr&gt; "Urban", "Urban", "Rural", "Urban", "Rural", "…
$ Smoking_History         &lt;chr&gt; "Yes", "No", "Yes", "No", "No", "No", "No", "Y…
$ Diabetes_History        &lt;chr&gt; "No", "No", "No", "No", "No", "No", "Yes", "No…
$ Hypertension_History    &lt;chr&gt; "No", "No", "No", "No", "No", "No", "Yes", "No…
$ Cholesterol_Level       &lt;dbl&gt; 186.4002, 185.1367, 210.6966, 211.1655, 223.81…
$ Physical_Activity       &lt;chr&gt; "Moderate", "Low", "Low", "Moderate", "High", …
$ Diet_Quality            &lt;chr&gt; "Poor", "Good", "Average", "Good", "Good", "Go…
$ Alcohol_Consumption     &lt;chr&gt; "Low", "Low", "Moderate", "High", "High", "Hig…
$ Stress_Levels           &lt;dbl&gt; 3.644786, 3.384056, 3.810911, 6.014878, 6.8068…
$ BMI                     &lt;dbl&gt; 33.96135, 28.24287, 27.60121, 23.71729, 19.771…
$ Heart_Rate              &lt;dbl&gt; 72.30153, 57.45764, 64.65870, 55.13147, 76.667…
$ Systolic_BP             &lt;dbl&gt; 123.90209, 129.89331, 145.65490, 131.78522, 10…
$ Diastolic_BP            &lt;dbl&gt; 85.68281, 73.52426, 71.99481, 68.21133, 92.902…
$ Family_History          &lt;chr&gt; "No", "Yes", "No", "No", "No", "No", "No", "No…
$ Heart_Attack_Occurrence &lt;chr&gt; "No", "No", "No", "No", "No", "No", "No", "No"…
$ Extra_Column_1          &lt;dbl&gt; 0.40498852, 0.03627815, 0.85297888, 0.39085280…
$ Extra_Column_2          &lt;dbl&gt; 0.43330004, 0.51256694, 0.21959083, 0.29684675…
$ Extra_Column_3          &lt;dbl&gt; 0.62871236, 0.66839275, 0.61343656, 0.15572404…
$ Extra_Column_4          &lt;dbl&gt; 0.70160955, 0.11552874, 0.50800995, 0.87025144…
$ Extra_Column_5          &lt;dbl&gt; 0.49814235, 0.42381938, 0.90066981, 0.39035591…
$ Extra_Column_6          &lt;dbl&gt; 0.007901312, 0.083932768, 0.227205241, 0.40318…
$ Extra_Column_7          &lt;dbl&gt; 0.79458257, 0.68895108, 0.49634358, 0.74140891…
$ Extra_Column_8          &lt;dbl&gt; 0.29077922, 0.83016364, 0.75210679, 0.22396813…
$ Extra_Column_9          &lt;dbl&gt; 0.49719307, 0.63449028, 0.18150125, 0.32931387…
$ Extra_Column_10         &lt;dbl&gt; 0.52199452, 0.30204337, 0.62918031, 0.14319054…
$ Extra_Column_11         &lt;dbl&gt; 0.79965663, 0.04368285, 0.01827617, 0.90778075…
$ Extra_Column_12         &lt;dbl&gt; 0.72239788, 0.45166789, 0.06322702, 0.54232201…
$ Extra_Column_13         &lt;dbl&gt; 0.1487387, 0.8786714, 0.1465122, 0.9224606, 0.…
$ Extra_Column_14         &lt;dbl&gt; 0.8340099, 0.5356022, 0.9972962, 0.6262165, 0.…
$ Extra_Column_15         &lt;dbl&gt; 0.061632229, 0.617825340, 0.974455410, 0.22860…</code></pre>
</div>
</div>
<p>Display only the first few rows after removing the Extra_Column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"Extra_Column"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Age Gender Region Smoking_History Diabetes_History Hypertension_History
1  56   Male  Urban             Yes               No                   No
2  69   Male  Urban              No               No                   No
3  46   Male  Rural             Yes               No                   No
4  32 Female  Urban              No               No                   No
5  60 Female  Rural              No               No                   No
6  25 Female  Rural              No               No                   No
  Cholesterol_Level Physical_Activity Diet_Quality Alcohol_Consumption
1          186.4002          Moderate         Poor                 Low
2          185.1367               Low         Good                 Low
3          210.6966               Low      Average            Moderate
4          211.1655          Moderate         Good                High
5          223.8143              High         Good                High
6          220.3400               Low         Good                High
  Stress_Levels      BMI Heart_Rate Systolic_BP Diastolic_BP Family_History
1      3.644786 33.96135   72.30153    123.9021     85.68281             No
2      3.384056 28.24287   57.45764    129.8933     73.52426            Yes
3      3.810911 27.60121   64.65870    145.6549     71.99481             No
4      6.014878 23.71729   55.13147    131.7852     68.21133             No
5      6.806883 19.77158   76.66792    100.6946     92.90249             No
6      8.207233 20.24744   67.66268    134.5966     73.14970             No
  Heart_Attack_Occurrence
1                      No
2                      No
3                      No
4                      No
5                      No
6                      No</code></pre>
</div>
</div>
<section id="check-for-duplicates" class="level4">
<h4 class="anchored" data-anchor-id="check-for-duplicates"><strong>Check for duplicates</strong></h4>
<p>Using the&nbsp;<code>duplicated</code>&nbsp;function, we see that there are no duplicate entries in the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df[<span class="fu">duplicated</span>(df),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Age                     Gender                  Region                 
 [4] Smoking_History         Diabetes_History        Hypertension_History   
 [7] Cholesterol_Level       Physical_Activity       Diet_Quality           
[10] Alcohol_Consumption     Stress_Levels           BMI                    
[13] Heart_Rate              Systolic_BP             Diastolic_BP           
[16] Family_History          Heart_Attack_Occurrence Extra_Column_1         
[19] Extra_Column_2          Extra_Column_3          Extra_Column_4         
[22] Extra_Column_5          Extra_Column_6          Extra_Column_7         
[25] Extra_Column_8          Extra_Column_9          Extra_Column_10        
[28] Extra_Column_11         Extra_Column_12         Extra_Column_13        
[31] Extra_Column_14         Extra_Column_15        
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
</section>
<section id="check-for-missing-values" class="level4">
<h4 class="anchored" data-anchor-id="check-for-missing-values">Check for missing values</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Age                  Gender                  Region 
                      0                       0                       0 
        Smoking_History        Diabetes_History    Hypertension_History 
                      0                       0                       0 
      Cholesterol_Level       Physical_Activity            Diet_Quality 
                      0                       0                       0 
    Alcohol_Consumption           Stress_Levels                     BMI 
                      0                       0                       0 
             Heart_Rate             Systolic_BP            Diastolic_BP 
                      0                       0                       0 
         Family_History Heart_Attack_Occurrence          Extra_Column_1 
                      0                       0                       0 
         Extra_Column_2          Extra_Column_3          Extra_Column_4 
                      0                       0                       0 
         Extra_Column_5          Extra_Column_6          Extra_Column_7 
                      0                       0                       0 
         Extra_Column_8          Extra_Column_9         Extra_Column_10 
                      0                       0                       0 
        Extra_Column_11         Extra_Column_12         Extra_Column_13 
                      0                       0                       0 
        Extra_Column_14         Extra_Column_15 
                      0                       0 </code></pre>
</div>
</div>
<p>✅ No missing values in the data, ready for use.<br>
✅ No duplicate entries, no need for deduplication.<br>
✅ Ready for data visualization and analysis.</p>
</section>
</section>
</section>
<section id="eda-1-heart-attack-occurrence-by-age-distribution" class="level2">
<h2 class="anchored" data-anchor-id="eda-1-heart-attack-occurrence-by-age-distribution">EDA 1 Heart Attack Occurrence by Age Distribution</h2>
<p>This stacked histogram visualizes the distribution of heart attack occurrences across different age groups.</p>
<p>The x-axis (Age) represents the age of individuals.The y-axis (Count) represents the number of individuals in each age group.</p>
<p>The bars are color-coded:Blue (“No”) represents individuals who did not experience a heart attack.Red (“Yes”) represents individuals who experienced a heart attack.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">fill =</span> Heart_Attack_Occurrence)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heart Attack Occurrence by Age Distribution"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"No"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"red"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="key-observations" class="level3">
<h3 class="anchored" data-anchor-id="key-observations"><strong>Key Observations:</strong></h3>
<ol type="1">
<li><p>The dataset has a relatively uniform distribution of individuals across different age groups, except for a slight drop in count near age 80.</p></li>
<li><p>Heart attacks (red section) appear in all age groups, but their proportion increases slightly with age.</p></li>
<li><p>Younger individuals (below 40) have a lower incidence of heart attacks, whereas older individuals (50+) show a higher proportion of heart attack occurrences.</p></li>
</ol>
<p>This visualization effectively highlights the relationship between age and heart attack occurrence, showing a general trend that older individuals are more likely to experience heart attacks.</p>
</section>
</section>
<section id="eda-2-heart-attack-occurrence-by-age-group" class="level2">
<h2 class="anchored" data-anchor-id="eda-2-heart-attack-occurrence-by-age-group">EDA 2 Heart Attack Occurrence by Age Group</h2>
<p>We could find there is a relationship between age and heart attack occurrence. So we can try to analysis the different heart attack occurrence from different age group.</p>
<p>Firstly, we define the age group, then we can calculate the heart attack rate, and finally we attempt to draw a stacked bar chart that allows us to directly observe the relationship between age and heart attack rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df_summary <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Age_Group =</span> <span class="fu">cut</span>(Age, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">35</span>, <span class="dv">50</span>, <span class="dv">65</span>, <span class="dv">80</span>), </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"18-35"</span>, <span class="st">"36-50"</span>, <span class="st">"51-65"</span>, <span class="st">"66-80"</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">right =</span> <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Age_Group, Heart_Attack_Occurrence) <span class="sc">%&gt;%</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Age_Group'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_summary, <span class="fu">aes</span>(<span class="at">x =</span> Age_Group, <span class="at">y =</span> Count, <span class="at">fill =</span> Heart_Attack_Occurrence)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.8</span>)) <span class="sc">+</span>  </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Count), </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.8</span>), </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>  </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heart Attack Occurrence by Age Group"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age Group"</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"No"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"red"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="key-observations-1" class="level3">
<h3 class="anchored" data-anchor-id="key-observations-1"><strong>Key Observations:</strong></h3>
<p>The total number of individuals decreases slightly as age increases.</p>
<ul>
<li><p>18-35 age group has the highest count (7487 individuals).</p></li>
<li><p>36-50, 51-65, and 66-80 age groups have relatively similar numbers (~6500-6600 individuals).</p></li>
<li><p>The absolute count of heart attack occurrences (red bars) is relatively stable across all age groups:</p>
<ul>
<li><p>18-35: 779 cases</p></li>
<li><p>36-50: 733 cases</p></li>
<li><p>51-65: 740 cases</p></li>
<li><p>66-80: 712 cases</p></li>
</ul>
<h4 id="key-insight" class="anchored"><strong>Key Insight:</strong></h4>
<ol type="1">
<li>The absolute number of heart attacks does not show a significant increase with age.</li>
<li>However, this does not account for population size differences. We need to look at heart attack rates for a better interpretation.</li>
</ol></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>df_rate <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Age_Group =</span> <span class="fu">cut</span>(Age, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">35</span>, <span class="dv">50</span>, <span class="dv">65</span>, <span class="dv">80</span>), </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"18-35"</span>, <span class="st">"36-50"</span>, <span class="st">"51-65"</span>, <span class="st">"66-80"</span>),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">right =</span> <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Age_Group) <span class="sc">%&gt;%</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Heart_Attack_Rate =</span> <span class="fu">mean</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"Yes"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_rate, <span class="fu">aes</span>(<span class="at">x =</span> Age_Group, <span class="at">y =</span> Heart_Attack_Rate, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>  </span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(Heart_Attack_Rate, <span class="dv">3</span>)),  </span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.4</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span>  </span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heart Attack Rate by Age Group"</span>,</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age Group"</span>,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Heart Attack Rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Heart attack rate is not strictly increasing with age.</strong></p>
<ul>
<li><p>The 18-35 group has the lowest rate (0.094).</p></li>
<li><p>The rate increases in the 36-50 group (0.101 or 10.1%) and peaks at 51-65 (0.104).</p></li>
<li><p>Surprisingly, the 66-80 group sees a slight decline (0.097) in heart attack rate.</p></li>
<li><p>The highest heart attack risk is in the 51-65 age group.</p></li>
</ul>
</section>
<section id="key-observations-2" class="level3">
<h3 class="anchored" data-anchor-id="key-observations-2"><strong>Key Observations:</strong></h3>
<p>✅ Heart attack risk is lowest in the youngest group (18-35) and peaks at 51-65.<br>
✅ The absolute number of heart attacks remains relatively stable across age groups.<br>
✅ The oldest group (66-80) shows a slight decrease in heart attack rate, possibly due to survivor bias or better health management.</p>
</section>
</section>
<section id="eda-2-the-relationship-between-gender-and-heart-attack" class="level2">
<h2 class="anchored" data-anchor-id="eda-2-the-relationship-between-gender-and-heart-attack">EDA 2 The relationship between gender and heart attack</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df_gender_rate <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Gender) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Heart_Attack_Rate =</span> <span class="fu">mean</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"Yes"</span>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_gender_rate, <span class="fu">aes</span>(<span class="at">x =</span> Gender, <span class="at">y =</span> Heart_Attack_Rate, <span class="at">fill =</span> Gender)) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span>  </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(Heart_Attack_Rate, <span class="dv">3</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heart Attack Rate by Gender"</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Gender"</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Heart Attack Rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="key-observations-3" class="level3">
<h3 class="anchored" data-anchor-id="key-observations-3"><strong>Key Observations:</strong></h3>
<p>Heart Attack Rate Comparison</p>
<p>The heart attack rate for males (0.102) is slightly higher than for females (0.096). The difference is small but noticeable, indicating that gender may have a minor impact on heart attack occurrence.</p>
<p>Gender-Specific Risk</p>
<p>Males tend to have a slightly higher likelihood of experiencing heart attacks. Females have a lower but still significant heart attack rate</p>
</section>
</section>
<section id="eda3-calculate-the-incidence-rate-of-heart-disease-in-different-regions" class="level2">
<h2 class="anchored" data-anchor-id="eda3-calculate-the-incidence-rate-of-heart-disease-in-different-regions">EDA3 Calculate the incidence rate of heart disease in different regions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>region_rate <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Region) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Heart_Attack_Rate =</span> <span class="fu">mean</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"Yes"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Heart_Attack_Rate))  </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(region_rate, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Region, <span class="sc">-</span>Heart_Attack_Rate), <span class="at">y =</span> Heart_Attack_Rate, <span class="at">fill =</span> Region)) <span class="sc">+</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(Heart_Attack_Rate, <span class="dv">4</span>)), </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span>  </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heart Attack Rate by Region"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Region"</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Heart Attack Rate"</span>) <span class="sc">+</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the above graph, the heart attack occurrence in Urban and Rural is the noticeable difference.</p>
</section>
<section id="eda4-the-relationship-between-health-conditions-and-heart-attack-occurrence" class="level2">
<h2 class="anchored" data-anchor-id="eda4-the-relationship-between-health-conditions-and-heart-attack-occurrence">EDA4 The relationship between health conditions and heart attack occurrence</h2>
<p>We need to compare the <strong>heart attack rate</strong> between individuals who have the condition and those who don’t.</p>
<section id="calculate-heart-attack-rates-for-each-health-factor" class="level3">
<h3 class="anchored" data-anchor-id="calculate-heart-attack-rates-for-each-health-factor">1.Calculate heart attack rates for each health factor</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate heart attack rates for each health factor</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>health_factors <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Smoking_Yes =</span> <span class="fu">mean</span>(Heart_Attack_Occurrence[Smoking_History <span class="sc">==</span> <span class="st">"Yes"</span>] <span class="sc">==</span> <span class="st">"Yes"</span>),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Smoking_No =</span> <span class="fu">mean</span>(Heart_Attack_Occurrence[Smoking_History <span class="sc">==</span> <span class="st">"No"</span>] <span class="sc">==</span> <span class="st">"Yes"</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Diabetes_Yes =</span> <span class="fu">mean</span>(Heart_Attack_Occurrence[Diabetes_History <span class="sc">==</span> <span class="st">"Yes"</span>] <span class="sc">==</span> <span class="st">"Yes"</span>),</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Diabetes_No =</span> <span class="fu">mean</span>(Heart_Attack_Occurrence[Diabetes_History <span class="sc">==</span> <span class="st">"No"</span>] <span class="sc">==</span> <span class="st">"Yes"</span>),</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Hypertension_Yes =</span> <span class="fu">mean</span>(Heart_Attack_Occurrence[Hypertension_History <span class="sc">==</span> <span class="st">"Yes"</span>] <span class="sc">==</span> <span class="st">"Yes"</span>),</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Hypertension_No =</span> <span class="fu">mean</span>(Heart_Attack_Occurrence[Hypertension_History <span class="sc">==</span> <span class="st">"No"</span>] <span class="sc">==</span> <span class="st">"Yes"</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to long format for visualization</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>health_factors_long <span class="ot">&lt;-</span> tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(health_factors, </span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">cols =</span> <span class="fu">everything</span>(), </span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">names_to =</span> <span class="fu">c</span>(<span class="st">"Condition"</span>, <span class="st">"Group"</span>),</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">names_sep =</span> <span class="st">"_"</span>,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">values_to =</span> <span class="st">"Heart_Attack_Rate"</span>)</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(health_factors_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Condition    Group Heart_Attack_Rate
  &lt;chr&gt;        &lt;chr&gt;             &lt;dbl&gt;
1 Smoking      Yes              0.102 
2 Smoking      No               0.0974
3 Diabetes     Yes              0.103 
4 Diabetes     No               0.0976
5 Hypertension Yes              0.101 
6 Hypertension No               0.0982</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot heart attack rate for each health condition with values displayed</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(health_factors_long, <span class="fu">aes</span>(<span class="at">x =</span> Group, <span class="at">y =</span> Heart_Attack_Rate, <span class="at">fill =</span> Group)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(Heart_Attack_Rate, <span class="dv">4</span>)),  <span class="co"># Display values rounded to 4 decimal places</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Condition, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span>  <span class="co"># Create separate graphs for each condition</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Impact of Health Conditions on Heart Attack Occurrence"</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Health Condition Group"</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Heart Attack Rate"</span>) <span class="sc">+</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"No"</span> <span class="ot">=</span> <span class="st">"blue"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="key-observations-4" class="level3">
<h3 class="anchored" data-anchor-id="key-observations-4"><strong>Key Observations:</strong></h3>
<p>Higher Heart Attack Rates for Individuals with Health Conditions:</p>
<p>The heart attack occurrence rate is slightly higher for individuals with a history of smoking, diabetes, and hypertension compared to those without.</p>
<p>Specifically:</p>
<p>Smoking: 10.2% for smokers vs.&nbsp;9.74% for non-smokers.</p>
<p>Diabetes: 10.33% for individuals with diabetes vs.&nbsp;9.76% for those without.</p>
<p>Hypertension: 10.08% for individuals with hypertension vs.&nbsp;9.82% for those without.</p>
<p>The findings suggest that smoking, diabetes, and hypertension slightly increase the likelihood of a heart attack, with diabetes having the most significant impact.</p>
</section>
<section id="analyze-the-impact-of-continuous-variables-cholesterol-bmi" class="level3">
<h3 class="anchored" data-anchor-id="analyze-the-impact-of-continuous-variables-cholesterol-bmi">2.Analyze the Impact of Continuous Variables (Cholesterol, BMI)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare Cholesterol Level and BMI for Heart Attack vs. No Heart Attack</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>numerical_health <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Heart_Attack_Occurrence) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Avg_Cholesterol =</span> <span class="fu">mean</span>(Cholesterol_Level, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Avg_BMI =</span> <span class="fu">mean</span>(BMI, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(numerical_health)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  Heart_Attack_Occurrence Avg_Cholesterol Avg_BMI
  &lt;chr&gt;                             &lt;dbl&gt;   &lt;dbl&gt;
1 No                                 200.    25.0
2 Yes                                200.    24.9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create boxplots for cholesterol and BMI</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>df_long <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(Cholesterol_Level, BMI), </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">names_to =</span> <span class="st">"Health_Metric"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_long, <span class="fu">aes</span>(<span class="at">x =</span> Heart_Attack_Occurrence, <span class="at">y =</span> Value, <span class="at">fill =</span> Heart_Attack_Occurrence)) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Health_Metric, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span> </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Comparison of Cholesterol Level and BMI in Heart Attack Cases"</span>,</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Heart Attack Occurrence"</span>,</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Value"</span>) <span class="sc">+</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"No"</span> <span class="ot">=</span> <span class="st">"blue"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="key-observations-5" class="level3">
<h3 class="anchored" data-anchor-id="key-observations-5"><strong>Key Observations:</strong></h3>
<p>The average cholesterol levels (199.91 vs.&nbsp;199.79) show almost no difference, suggesting that cholesterol level alone may not be a strong distinguishing factor for heart attack risk.</p>
<p>The average BMI values (25.01 vs.&nbsp;24.91) are very close, indicating no significant difference between the two groups.</p>
<p>Cholesterol levels and BMI are nearly identical between those who experienced a heart attack and those who did not, suggesting they might not be the primary driving factors for heart attacks in this dataset.</p>
</section>
<section id="draw-a-heat-map" class="level3">
<h3 class="anchored" data-anchor-id="draw-a-heat-map">3. Draw a heat map</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df_numeric <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Heart_Attack_Occurrence =</span> <span class="fu">ifelse</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Smoking_History =</span> <span class="fu">ifelse</span>(Smoking_History <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Diabetes_History =</span> <span class="fu">ifelse</span>(Diabetes_History <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Hypertension_History =</span> <span class="fu">ifelse</span>(Hypertension_History <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Heart_Attack_Occurrence, Smoking_History, Diabetes_History, Hypertension_History, </span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>         Cholesterol_Level, BMI)  </span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>df_numeric <span class="ot">&lt;-</span> df_numeric <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(df_numeric, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrplot</span>(cor_matrix, <span class="at">lab =</span> <span class="cn">TRUE</span>, <span class="at">hc.order =</span> <span class="cn">TRUE</span>, <span class="at">type =</span> <span class="st">"lower"</span>, <span class="at">colors =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"white"</span>, <span class="st">"red"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Heart_Attack_Occurrence =</span> <span class="fu">ifelse</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Smoking_History =</span> <span class="fu">ifelse</span>(Smoking_History <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Diabetes_History =</span> <span class="fu">ifelse</span>(Diabetes_History <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Hypertension_History =</span> <span class="fu">ifelse</span>(Hypertension_History <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Cholesterol_Level =</span> <span class="fu">scale</span>(Cholesterol_Level),  </span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">BMI =</span> <span class="fu">scale</span>(BMI)  </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Heart_Attack_Occurrence <span class="sc">~</span> Smoking_History <span class="sc">+</span> Diabetes_History <span class="sc">+</span> Hypertension_History <span class="sc">+</span> </span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>                                       Cholesterol_Level <span class="sc">+</span> BMI, </span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> df, <span class="at">family =</span> <span class="fu">binomial</span>())</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Heart_Attack_Occurrence ~ Smoking_History + Diabetes_History + 
    Hypertension_History + Cholesterol_Level + BMI, family = binomial(), 
    data = df)

Coefficients:
                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)          -2.24672    0.02773 -81.015   &lt;2e-16 ***
Smoking_History       0.05125    0.04189   1.223    0.221    
Diabetes_History      0.06251    0.04739   1.319    0.187    
Hypertension_History  0.02956    0.04452   0.664    0.507    
Cholesterol_Level    -0.00360    0.01935  -0.186    0.852    
BMI                  -0.01728    0.01935  -0.893    0.372    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 19346  on 29999  degrees of freedom
Residual deviance: 19342  on 29994  degrees of freedom
AIC: 19354

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</section>
<section id="key-observations-6" class="level3">
<h3 class="anchored" data-anchor-id="key-observations-6"><strong>Key Observations:</strong></h3>
<p>Correlation Heatmap:</p>
<p>The heatmap shows very weak correlations between heart attack occurrence and other health factors.</p>
<p>All correlation values are close to zero, suggesting that none of the selected health factors strongly correlate with heart attack occurrence.</p>
<p>The highest correlation is only 0.01, which is negligible.</p>
<p>There are also weak correlations among other health-related variables, implying that these factors do not exhibit strong interdependencies in this dataset.</p>
<p>Logistic Regression Results:</p>
<p>The logistic regression model was used to analyze the relationship between health factors and heart attack occurrence.</p>
<p>None of the predictor variables (Smoking History, Diabetes History, Hypertension History, Cholesterol Level, BMI) were statistically significant in predicting heart attack occurrence (p-values &gt; 0.05 for all variables).</p>
<p>The intercept is significant, indicating that the base probability of heart attack occurrence (without considering the predictor variables) is non-trivial.</p>
<p>The estimated coefficients suggest that:Smoking history and diabetes history have positive coefficients, indicating a slight increase in heart attack occurrence. Cholesterol level and BMI have negative coefficients.</p>
<p>Both the logistic regression model and the correlation analysis suggest that the selected health factors (Smoking, Diabetes, Hypertension, Cholesterol Level, and BMI) do not significantly contribute to predicting heart attack occurrence in this dataset.</p>
</section>
</section>
<section id="eda5-the-relationship-between-stress-level-and-heart-attack-occurrence" class="level2">
<h2 class="anchored" data-anchor-id="eda5-the-relationship-between-stress-level-and-heart-attack-occurrence">EDA5 The relationship between stress level and heart attack occurrence</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/japan_heart_attack_dataset.csv"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Heart_Attack_Occurrence =</span> <span class="fu">ifelse</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Stress_Category =</span> <span class="fu">case_when</span>(</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    Stress_Levels <span class="sc">&gt;=</span> <span class="dv">0</span> <span class="sc">&amp;</span> Stress_Levels <span class="sc">&lt;=</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Low"</span>,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    Stress_Levels <span class="sc">&gt;</span> <span class="dv">3</span> <span class="sc">&amp;</span> Stress_Levels <span class="sc">&lt;=</span> <span class="dv">6</span> <span class="sc">~</span> <span class="st">"Moderate"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    Stress_Levels <span class="sc">&gt;</span> <span class="dv">6</span> <span class="sc">&amp;</span> Stress_Levels <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"High"</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>stress_impact <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Stress_Category) <span class="sc">%&gt;%</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_Count =</span> <span class="fu">n</span>(),  </span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">Heart_Attack_Count =</span> <span class="fu">sum</span>(Heart_Attack_Occurrence),  </span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">Heart_Attack_Rate =</span> <span class="fu">mean</span>(Heart_Attack_Occurrence)  </span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(stress_impact)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Stress_Category Total_Count Heart_Attack_Count Heart_Attack_Rate
  &lt;chr&gt;                 &lt;int&gt;              &lt;dbl&gt;             &lt;dbl&gt;
1 High                   9279                874            0.0942
2 Low                    4698                504            0.107 
3 Moderate              16023               1586            0.0990</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(stress_impact, <span class="fu">aes</span>(<span class="at">x =</span> Stress_Category, <span class="at">y =</span> Heart_Attack_Rate, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>  </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(Heart_Attack_Rate, <span class="dv">4</span>)),  </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span>  </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heart Attack Rate by Stress Level"</span>,</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Stress Level Category"</span>,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Heart Attack Rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Heart Attack Rate Across Stress Levels:</p>
<p>The heart attack rate is highest in the low stress category (10.73%).</p>
<p>The moderate stress category has a slightly lower heart attack rate (9.99%).</p>
<p>The high stress category has the lowest heart attack rate (9.42%).</p>
</section>
<section id="eda6-exploring-the-impact-of-lifestyle-level-of-physical-activitydietary-qualityalcohol-intake-on-the-onset-of-heart-disease" class="level2">
<h2 class="anchored" data-anchor-id="eda6-exploring-the-impact-of-lifestyle-level-of-physical-activitydietary-qualityalcohol-intake-on-the-onset-of-heart-disease">EDA6 Exploring the impact of lifestyle (level of physical activity\dietary quality\alcohol intake) on the onset of heart disease</h2>
<section id="the-impact-of-physical-activity-level-on-heart-attack" class="level3">
<h3 class="anchored" data-anchor-id="the-impact-of-physical-activity-level-on-heart-attack">1. The impact of physical activity level on heart attack</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Physical_Activity =</span> <span class="fu">factor</span>(Physical_Activity, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Moderate"</span>, <span class="st">"High"</span>)),</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Heart_Attack_Occurrence =</span> <span class="fu">as.numeric</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"Yes"</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Heart_Attack_Occurrence, <span class="at">y =</span> Physical_Activity, <span class="at">fill =</span> ..x..)) <span class="sc">+</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density_ridges_gradient</span>(<span class="at">scale =</span> <span class="dv">2</span>, <span class="at">rel_min_height =</span> <span class="fl">0.01</span>) <span class="sc">+</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span>  </span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heart Attack Occurrence Distribution by Physical Activity Level"</span>,</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Heart Attack Occurrence Probability"</span>,</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Physical Activity Level"</span>,</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..x..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(x)` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Picking joint bandwidth of 0.143</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of heart attack occurrence probability is similar across different physical activity levels (High, Moderate, Low).</p>
</section>
<section id="the-impact-of-dietary-quality-on-heart-attack" class="level3">
<h3 class="anchored" data-anchor-id="the-impact-of-dietary-quality-on-heart-attack">2. The impact of Dietary quality on heart attack</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Diet_Quality =</span> <span class="fu">factor</span>(Diet_Quality, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Poor"</span>, <span class="st">"Average"</span>, <span class="st">"Good"</span>)),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Heart_Attack_Occurrence =</span> <span class="fu">as.numeric</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"Yes"</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Heart_Attack_Occurrence, <span class="at">y =</span> Diet_Quality, <span class="at">fill =</span> ..x..)) <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density_ridges_gradient</span>(<span class="at">scale =</span> <span class="dv">2</span>, <span class="at">rel_min_height =</span> <span class="fl">0.01</span>) <span class="sc">+</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span>  </span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heart Attack Occurrence Distribution by Diet Quality"</span>,</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Heart Attack Occurrence Probability"</span>,</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Diet Quality"</span>,</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Picking joint bandwidth of 0.144</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>All three categories show overlapping probability distributions, meaning diet quality alone may not be a decisive factor for heart attack occurrence.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Alcohol_Consumption =</span> <span class="fu">factor</span>(Alcohol_Consumption, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"None"</span>, <span class="st">"Low"</span>, <span class="st">"Moderate"</span>, <span class="st">"High"</span>)),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Heart_Attack_Occurrence =</span> <span class="fu">as.numeric</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"Yes"</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Heart_Attack_Occurrence, <span class="at">y =</span> Alcohol_Consumption, <span class="at">fill =</span> ..x..)) <span class="sc">+</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density_ridges_gradient</span>(<span class="at">scale =</span> <span class="dv">2</span>, <span class="at">rel_min_height =</span> <span class="fl">0.01</span>) <span class="sc">+</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span>  </span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heart Attack Occurrence Distribution by Alcohol Consumption Level"</span>,</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Heart Attack Occurrence Probability"</span>,</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Alcohol Consumption Level"</span>,</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Picking joint bandwidth of 0.156</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution <strong>remains centered</strong> around a similar probability range for all levels of alcohol consumption.</p>
</section>
</section>
<section id="summary-and-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="summary-and-conclusion">Summary and conclusion</h2>
<p>In this analysis, we explored various factors related to heart attack occurrence, including age, gender, lifestyle choices, and health conditions. Through data visualization and statistical modeling, we examined their potential impact on heart disease risk. The key findings are:</p>
<p>Age and Heart Attack Risk: Heart attack occurrence is not strictly increasing with age. While the absolute number of cases is relatively stable across age groups, the heart attack rate is lowest in the youngest group (18-35) and peaks in the 51-65 age group before slightly decreasing in the oldest (66-80) group.</p>
<p>Gender Influence: Males have a slightly higher heart attack rate (10.2%) compared to females (9.6%). Though the difference is small, it suggests a minor gender-based variation in heart attack susceptibility.</p>
<p>Impact of Health Conditions: Individuals with a history of smoking, diabetes, and hypertension show slightly higher heart attack rates compared to those without these conditions. Among these, diabetes has the most noticeable effect, with a heart attack rate of 10.33% for diabetics versus 9.76% for non-diabetics.</p>
<p>Cholesterol and BMI Effects: The average cholesterol levels and BMI values between individuals who experienced heart attacks and those who did not are nearly identical.</p>
<p>Lifestyle Factors: The influence of physical activity, diet quality, and alcohol consumption on heart attack occurrence appears to be minimal. The probability distributions for heart attack occurrences remain similar across all categories within these factors, suggesting that none of them are strong standalone predictors of heart attacks.</p>
<p>Given the weak correlations and the non-significant predictors in logistic regression, further studies with more comprehensive datasets and additional health indicators may be necessary to develop a more accurate risk assessment model for heart attacks. Statistical hypothesis testing and more advanced modeling techniques could provide deeper insights into the complex relationships between these factors and heart disease risk.</p>
<p>At last, this exercise was a helpful way to practice presenting data effectively, and create data visualization.</p>
</section>
<section id="reference" class="level2">
<h2 class="anchored" data-anchor-id="reference">Reference:</h2>
<ul>
<li><p><a href="https://webfs.oecd.org/pisa2022/CY08MSP_CODEBOOK_5thDecember23.xlsx">Code Book</a></p></li>
<li><p><a href="https://isss608-spacebun.netlify.app/take-home_ex/take-home_ex1/take-home_ex1">LEW YING ZHEN SERENA</a></p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>